#!/usr/bin/env python3
"""Merge the claim-registry fragments Alignment/claims/<Group>.yaml into Alignment/claims.yaml
and write the blind extract Alignment/claims_blind.yaml (id, group, source, text only).

The fragments are the source of truth and are never modified. Validation problems are
printed (and returned with exit code 0; the scorer turns them into registration flags).

Usage: python scripts/sa_merge_claims.py [--root PROOFS_DIR] [--check-sources]
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import sa_claims_lib as L  # noqa: E402

HEADER = ("# GENERATED by scripts/sa_merge_claims.py from Alignment/claims/*.yaml. Do not edit:\n"
          "# edit the fragment of the claim's group instead.\n")
BLIND_HEADER = ("# GENERATED blind extract (id, group, source, text only). This is the ONLY registry\n"
                "# file blind shadow authors may read.\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(pathlib.Path(__file__).resolve().parent.parent))
    ap.add_argument("--check-sources", action="store_true",
                    help="verify that every text fragment occurs verbatim in its cited lines")
    args = ap.parse_args()
    root = pathlib.Path(args.root)
    frag_dir = root / "Alignment" / "claims"
    files = sorted(frag_dir.glob("*.yaml")) if frag_dir.exists() else []
    claims: list[dict] = []
    problems: list[str] = []
    for f in files:
        try:
            cs = L.load_claims_file(f)
        except Exception as e:  # noqa: BLE001
            problems.append(f"{f.name}: cannot parse ({e})")
            continue
        for c in cs:
            if L.is_example_id(str(c.get("id", ""))):
                problems.append(f"{f.name}: {c.get('id')}: SELFTEST./EXAMPLE. ids are reserved")
                continue
            if str(c.get("group", "")) != f.stem:
                problems.append(f"{f.name}: {c.get('id')}: group `{c.get('group')}` differs from the "
                                f"fragment name `{f.stem}`")
            claims.append(c)
    seen: dict[str, int] = {}
    for c in claims:
        cid = str(c.get("id", ""))
        seen[cid] = seen.get(cid, 0) + 1
        for p in L.validate_claim(c):
            problems.append(f"{cid}: {p}")
        if args.check_sources:
            sp = L.source_problem(c, root)
            if sp:
                problems.append(f"{cid}: {sp}")
    for cid, k in seen.items():
        if k > 1:
            problems.append(f"{cid}: duplicate id ({k} entries)")
    merged = []
    for c in claims:
        out = {k: c.get(k) for k in L.FIELDS if k in c}
        for k, v in c.items():
            if k not in out and not k.startswith("_"):
                out[k] = v
        merged.append(out)
    blind = [{k: c.get(k) for k in ("id", "group", "source", "text")} for c in claims]
    L.dump_yaml(merged, root / "Alignment" / "claims.yaml", HEADER)
    L.dump_yaml(blind, root / "Alignment" / "claims_blind.yaml", BLIND_HEADER)
    print(f"merged {len(claims)} claim(s) from {len(files)} fragment(s) into Alignment/claims.yaml "
          f"and Alignment/claims_blind.yaml")
    if problems:
        print(f"{len(problems)} registry problem(s):")
        for p in problems[:200]:
            print("  - " + p)
        if len(problems) > 200:
            print(f"  ... {len(problems) - 200} more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
